'use strict';

// ============================================================================
//  core/dom.js —— DOM 引用的集中缓存
//  el 里的每个字段都是页面加载时取一次的节点引用（全项目都在用它）。
//  注意：module 脚本要等 HTML 解析完才执行，所以这里取节点是安全的。
// ============================================================================

const $ = (id) => document.getElementById(id);

export const el = {
  convoList: $('convo-list'),
  // 会话列表头上的分组标签（「最近 · 5」，条数由 renderConvoList 填）
  convoCap: $('convo-cap'),
  convoTitle: $('convo-title'),
  convoMeta: $('convo-meta'),
  // 顶栏左边那颗头像 + 标题旁边的小胶囊（都是 renderHeader 填的）
  topbarAvatar: $('topbar-avatar'),
  convoPill: $('convo-pill'),
  messages: $('messages'),
  input: $('input'),
  hintText: $('hint-text'),
  usageText: $('usage-text'),
  btnNew: $('btn-new'),
  btnSend: $('btn-send'),
  btnAttach: $('btn-attach'),
  attachStrip: $('attach-strip'),
  btnStop: $('btn-stop'),
  btnClear: $('btn-clear'),
  btnCopyAll: $('btn-copy-all'),
  btnSettings: $('btn-settings'),
  btnFolder: $('btn-folder'),
  btnChars: $('btn-chars'),
  btnWorldbooks: $('btn-worldbooks'),
  btnPresets: $('btn-presets'),
  // 帮助页（内容是静态文本，没有 render 函数，只靠 viewSwitch 显隐）
  btnHelp: $('btn-help'),
  btnTheme: $('btn-theme'),
  btnAccent: $('btn-accent'),
  modal: $('settings-modal'),
  btnCloseSettings: $('btn-close-settings'),
  btnSaveSettings: $('btn-save-settings'),
  btnTest: $('btn-test'),
  btnFetchModels: $('btn-fetch-models'),
  btnAddProvider: $('btn-add-provider'),
  btnDelProvider: $('btn-del-provider'),
  providerTabs: $('provider-tabs'),
  providerPresets: $('provider-presets'),
  // 顶栏切换模型：按钮 + 它下面的弹层（自绘的，不是原生 select —— 见 ui/modelMenu.js）
  modelSwitch: $('model-switch'),
  modelSwitchLabel: $('model-switch-label'),
  modelMenu: $('model-menu'),
  // 状态卡入口条（点头像开各人的状态卡）—— 一行，排在消息区上面
  panelBox: $('panel-box'),
  panelCast: $('panel-cast'),
  // 「在场角色 N」里的那个数字，条数由 panelUi 的 renderPanelCast 填
  panelCastCount: $('panel-cast-count'),
  // 「全部展开 / 全部收起」批量开关（在入口条那一行的右端）
  btnCardsAll: $('btn-cards-all'),
  // 浮动状态卡的容器（铺满对话列、本身不挡鼠标，只有卡片实体可交互）
  stateCards: $('state-cards'),
  // 对话窗口外观
  btnAppearance: $('btn-appearance'),
  appearanceModal: $('appearance-modal'),
  appearanceFontSize: $('appearance-fontsize'),
  appearanceFontSizeValue: $('appearance-fontsize-value'),
  appearanceBoldColor: $('appearance-boldcolor'),
  appearanceBoldColorText: $('appearance-boldcolor-text'),
  appearanceBgPreview: $('appearance-bg-preview'),
  btnPickBg: $('btn-pick-bg'),
  btnClearBg: $('btn-clear-bg'),
  btnBoldColorReset: $('btn-boldcolor-reset'),
  btnCloseAppearance: $('btn-close-appearance'),
  btnCloseAppearance2: $('btn-close-appearance-2'),
  // 视角设置
  btnPerspective: $('btn-perspective'),
  // 顶栏「⋯」菜单：记忆 / 复制全文 / 导出 / 清空对话 都收在里面（见 ui/menu.js）
  btnMore: $('btn-more'),
  moreMenu: $('topbar-more'),
  // 「⋯」上的小圆点：菜单里藏着东西（比如有记忆摘要）时提示一下，不然收起来就看不见了
  moreDot: $('more-dot'),
  // 「帮我想想」的建议条
  suggestStrip: $('suggest-strip'),
  suggestList: $('suggest-list'),
  btnSuggestClose: $('btn-suggest-close'),
  perspectiveModal: $('perspective-modal'),
  btnClosePerspective: $('btn-close-perspective'),
  btnClosePerspective2: $('btn-close-perspective-2'),
  pNarration: $('p-narration'),
  pPace: $('p-pace'),
  pGm: $('p-gm'),
  pPresetList: $('p-preset-list'),
  // 记忆
  btnMemory: $('btn-memory'),
  memoryCount: $('memory-count'),
  memoryModal: $('memory-modal'),
  btnCloseMemory: $('btn-close-memory'),
  btnCloseMemory2: $('btn-close-memory-2'),
  btnSaveCheckpoint: $('btn-save-checkpoint'),
  checkpointList: $('checkpoint-list'),
  memorySummaryLine: $('memory-summary-line'),
  memoryPendingLine: $('memory-pending-line'),
  memoryList: $('memory-list'),
  btnSummarizeNow: $('btn-summarize-now'),
  btnMemoryClear: $('btn-memory-clear'),
  memoryFootHint: $('memory-foot-hint'),
  confirmModal: $('confirm-modal'),
  confirmTitle: $('confirm-title'),
  confirmMessage: $('confirm-message'),
  confirmOk: $('confirm-ok'),
  confirmCancel: $('confirm-cancel'),
  toast: $('toast'),
  // 角色库
  charsModal: $('chars-modal'),
  charsTitle: $('chars-title'),
  charsSub: $('chars-sub'),
  // 主区域的五个视图：聊天 / 角色列表页 / 世界书列表页 / 预设列表页 / 帮助页
  viewChat: $('view-chat'),
  viewChars: $('view-chars'),
  viewWorldbooks: $('view-worldbooks'),
  viewPresets: $('view-presets'),
  viewHelp: $('view-help'),
  // 帮助页右上角「复制优化提示词」（文本在 views/help.js）
  btnCopyHelpPrompt: $('btn-copy-help-prompt'),
  charsPageSub: $('chars-page-sub'),
  charPageGrid: $('char-page-grid'),
  charPageEmpty: $('char-page-empty'),
  wbPageSub: $('wb-page-sub'),
  wbPageGrid: $('wb-page-grid'),
  wbPageEmpty: $('wb-page-empty'),
  presetPageSub: $('preset-page-sub'),
  presetPageGrid: $('preset-page-grid'),
  presetPageEmpty: $('preset-page-empty'),
  btnNewPreset: $('btn-new-preset'),
  btnImportPreset: $('btn-import-preset'),
  btnExportPresets: $('btn-export-presets'),
  // 进入世界前先创建玩家自己的角色
  playerModal: $('player-modal'),
  playerTitle: $('player-title'),
  playerSub: $('player-sub'),
  playerName: $('player-name'),
  playerProfile: $('player-profile'),
  playerCharField: $('player-char-field'),
  playerChar: $('player-char'),
  playerCharPreview: $('player-char-preview'),
  btnClosePlayer: $('btn-close-player'),
  btnCancelPlayer: $('btn-cancel-player'),
  btnStartPlay: $('btn-start-play'),
  playerFootHint: $('player-foot-hint'),
  btnCloseChars: $('btn-close-chars'),
  btnImportCard: $('btn-import-card'),
  btnAiChar: $('btn-ai-char'),
  btnNewChar: $('btn-new-char'),
  btnDelChar: $('btn-del-char'),
  btnSaveChar: $('btn-save-char'),
  btnExportChar: $('btn-export-char'),
  btnExportConvo: $('btn-export-convo'),
  btnAddAttr: $('btn-add-attr'),
  charEmpty: $('char-empty'),
  charForm: $('char-form'),
  charAvatar: $('char-avatar'),
  btnClearAvatar: $('btn-clear-avatar'),
  charPortrait: $('char-portrait'),
  btnClearPortrait: $('btn-clear-portrait'),
  charExprList: $('char-expr-list'),
  btnAddExpr: $('btn-add-expr'),
  btnBatchExpr: $('btn-batch-expr'),
  // 表情图弹窗（挂在角色编辑器之上）
  exprModal: $('expr-modal'),
  exprCount: $('expr-count'),
  btnCloseExpr: $('btn-close-expr'),
  btnExprDone: $('btn-expr-done'),
  // 角色编辑器里那行「表情图 · 已设 N 条 · 管理」
  btnManageExpr: $('btn-manage-expr'),
  charExprSummary: $('char-expr-summary'),
  charFootHint: $('char-foot-hint'),
  c: {
    name: $('c-name'),
    tags: $('c-tags'),
    desc: $('c-desc'),
    personality: $('c-personality'),
    scenario: $('c-scenario'),
    first: $('c-first'),
    example: $('c-example'),
    system: $('c-system'),
    post: $('c-post'),
    notes: $('c-notes'),
    // 年龄/性别/种族**没有**输入框：这些是角色的固定设定，写进「角色描述」里。
    // （index.html 里那三个 id 早删了，这里曾经留着三个指向 null 的键 —— 别加回来。）
    attrNew: $('c-attr-new'),
    btnAttrTemplate: $('btn-attr-template'),
    // 分组标签栏：属性按分组切开，点哪个标签就只看哪一组
    attrTabs: $('c-attr-tabs'),
    attrQuick: $('c-attr-quick'),
    attrList: $('c-attr-list'),
    // 分组操作条（改名 / 解散），铺在字段列表上面
    attrGroupEdit: $('c-attr-group-edit'),
    btnAttrPaste: $('btn-attr-paste'),
    attrPaste: $('c-attr-paste'),
    // 剧情选项：开关 + 数量 + 额外要求
    optionsOn: $('c-options-on'),
    optionsConfig: $('c-options-config'),
    optionsCount: $('c-options-count'),
    optionsHint: $('c-options-hint'),
    // 在状态栏显示（`showInPanel`）：只对世界书副本有意义
    showInPanelBox: $('c-show-in-panel-box'),
    showInPanel: $('c-show-in-panel'),
    showInPanelHelp: $('c-show-in-panel-help'),
    // 角色自带的世界书：清单 + 绑定按钮 + 开关
    wbBox: $('c-worldbook-box'),
    wbList: $('c-wb-list'),
    wbAddBtn: $('c-wb-add-btn'),
    wbSwitch: $('c-wb-switch'),
    wbEnabled: $('c-wb-enabled'),
    wbDesc: $('c-wb-desc'),
    wbHint: $('c-wb-hint'),
    attrPasteText: $('c-attr-paste-text'),
    btnAttrPasteApply: $('btn-attr-paste-apply')
  },
  s: {
    temp: $('s-temp'),
    maxTokens: $('s-maxtokens'),
    sendOnEnter: $('s-sendonenter'),
    showDate: $('s-showdate'),
    showUsage: $('s-showusage'),
    autoContinue: $('s-autocontinue'),
    wbDepth: $('s-wb-depth'),
    imageProvider: $('s-image-provider'),
    imageModel: $('s-image-model'),
    imageSize: $('s-image-size'),
    ragEnabled: $('s-rag-enabled'),
    embeddingProvider: $('s-embedding-provider'),
    embeddingModel: $('s-embedding-model'),
    commonAttrs: $('s-commonattrs')
  },
  p: {
    name: $('p-name'),
    baseUrl: $('p-baseurl'),
    apiKey: $('p-apikey'),
    models: $('p-models')
  },
  // 预设编辑器
  pr: {
    modal: $('preset-modal'),
    title: $('preset-title'),
    sub: $('preset-sub'),
    name: $('pr-name'),
    tags: $('pr-tags'),
    note: $('pr-note'),
    content: $('pr-content'),
    enabled: $('pr-enabled'),
    global: $('pr-global'),
    temperature: $('pr-temperature'),
    maxTokens: $('pr-maxtokens'),
    topP: $('pr-topp'),
    footHint: $('pr-foot-hint'),
    btnClose: $('btn-close-preset'),
    btnClose2: $('btn-close-preset-2'),
    btnSave: $('btn-save-preset'),
    btnDel: $('btn-del-preset')
  },
  // 世界书
  wb: {
    modal: $('worldbooks-modal'),
    btnClose: $('btn-close-worldbooks'),
    btnClose2: $('btn-close-worldbooks-2'),
    btnImport: $('btn-import-lorebook'),
    btnNew: $('btn-new-worldbook'),
    entriesEmpty: $('wb-entries-empty'),
    entriesWrap: $('wb-entries-wrap'),
    name: $('wb-name'),
    opening: $('wb-opening'),
    entryCount: $('wb-entry-count'),
    entryList: $('wb-entry-list'),
    btnPreview: $('btn-preview-wb'),
    btnNewEntry: $('btn-new-entry'),
    btnExport: $('btn-export-wb'),
    btnDelBook: $('btn-del-worldbook'),
    charList: $('wb-char-list'),
    btnAddChars: $('btn-add-wb-chars'),
    btnAiChar: $('btn-ai-wb-char'),
    btnNewChar: $('btn-new-wb-char'),
    btnSyncAttrs: $('btn-sync-wb-attrs'),
    formEmpty: $('wb-form-empty'),
    form: $('wb-form'),
    footHint: $('wb-foot-hint'),
    dirtyHint: $('wb-dirty-hint'),
    btnSave: $('btn-save-wb'),
    e: {
      title: $('wb-e-title'),
      keys: $('wb-e-keys'),
      content: $('wb-e-content'),
      order: $('wb-e-order'),
      prob: $('wb-e-prob'),
      keys2: $('wb-e-keys2'),
      logic: $('wb-e-logic'),
      constant: $('wb-e-constant'),
      recursive: $('wb-e-recursive'),
      enabled: $('wb-e-enabled')
    },
    btnDelEntry: $('btn-del-entry')
  },
  // 从角色库多选加入世界书
  wbPicker: {
    modal: $('wb-char-picker'),
    list: $('wb-char-picker-list'),
    hint: $('wb-char-picker-hint'),
    btnClose: $('btn-close-wb-char-picker'),
    btnCancel: $('btn-cancel-wb-char-picker'),
    btnConfirm: $('btn-confirm-wb-char-picker')
  }
};
